---
title: "Pset 08 "
author: "hongye xuan"
date: "`r Sys.Date()`"
format: html
execute:
  echo: true   # Show all code
  eval: true   # Ensure all code runs
  warning: false
  message: false
---

```{r eval=TRUE}
x <- matrix(rnorm(1000), 100, 10); x[1:5, 1:4]

```

```{r eval=TRUE}
dim(x); nrow(x); ncol(x)

```

```{r eval=TRUE}
y <- x + 1:100; y[1:5, 1:4]

```

```{r eval=TRUE}
z <- sweep(y, 2, 2*(1:10), FUN = "+"); z[1:5, 1:4]

```

```{r eval=TRUE}
rowMeans(z)[1:10]

```

```{r eval=TRUE}
as.vector(matrix(1/nrow(z), 1, nrow(z)) %*% z)[1:10]

```

```{r eval=TRUE}
as.vector(sqrt((t(z)^2 %*% rep(1/nrow(z), nrow(z))) - (as.vector(matrix(1/nrow(z), 1, nrow(z)) %*% z)^2)))

```

```{r eval=TRUE}
library(dslabs)
mnist <- read_mnist()
gray_area <- mnist$train$images >= 50 & mnist$train$images <= 205
mean(gray_area)

```

```{r eval=TRUE}
sapply(0:9, function(d) {
  idx <- mnist$train$labels == d
  mean(mnist$train$images[idx, ] >= 50 & mnist$train$images[idx, ] <= 205)
})

```

```{r eval=TRUE}
gray_proportion <- rowMeans(mnist$train$images >= 50 & mnist$train$images <= 205)
boxplot(gray_proportion ~ mnist$train$labels, 
        xlab = "Digit", ylab = "Gray Pixel Proportion", 
        main = "Boxplot of Gray Pixel Proportion by Digit")

```

```{r eval=TRUE}
solve(matrix(c(1,2,-2,2,1,-5,1,-4,1), 3, 3), c(-15,-21,18))

```
